# Lightweight Linux distro as the base image
FROM alpine:latest

# Install required dependencies
RUN apk add --no-cache openssh-server

# Copy SSH config files
COPY config/ssh/sshd_config /etc/ssh/
COPY config/ssh/banner.txt /etc/ssh/

# Copy pre-generated SSH host keys
COPY config/ssh/ssh_keys/* /etc/ssh/

# Create .ssh directory and add authorized_keys file with dummy credentials
RUN mkdir -p /root/.ssh && \
    chmod 700 /root/.ssh && \
    echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC671Vlp/8NnE3cUCciEQ+adqohmTwFEMOaGwLl5nrrkb4iJR4ZdULTMH6FzK21F1ALYBpjb7YFmRVuTmwqveJYrLz5wcbgDYdAGloUcoAvZ3BHGiOOV7bSHUs2JK2SiDcfa6XaBs6bthzBJgmG3sDz0gROxSZguqxL2IRBKGHGdZsUG1VY6DjZrV3PWCoEP+0Mwp2vJh1I+eK4Y09Nvm1cysreelX7ZlWvg0ffjsRjENHFvTEMHXl06cvygyYPf5pqiTCZQpRNt+q1Z44jEPy1CsIAmXs4YwPx675IoLhATIL0ACOURSYubEyA3thREW/v5r89E0BCtU1Yrj8RknEDvfQzrLriNlf9NZvsfFOvWkp19xhFK3ZtOw2WfCzDvAyFtsLeMFofUklOFXLNjfsd6KUCVjIiivf3m8Sos9+n4rtX6HjWBCQtjzOBdVZHwX07l43DZ1fTo7pJDIdxZ2fBKUJk/GU0vnS4NBbTEBJNoHLrhiI/jcrXoEuOUC5Zl8WsDX3PKaRi9AEM0RX2v52HyGZX3x1iQ2C1+i1ACHFc1TO0Ti9HcSNWe/ueVmLOQpmZtB12z8yCsGVEXizsNyWTYcElGSl7DbiKHkpfc34jojlgPKNkW/3ny5lxMJR9jVHjansUKshMcQdLTT2N57qX4a4PzrJOpxCrSw3nAHsj+Q== root@preetham-ubuntu-desktop" > /root/.ssh/authorized_keys && \
    chmod 600 /root/.ssh/authorized_keys

# Expose SSH port
EXPOSE 2222 22

# Start SSH service
CMD ["/usr/sbin/sshd", "-D"]
