version: '3'

services:
  tor-server:
    build:
      context: .
      dockerfile: Dockerfile_tor_server
    ports:
      - "9051:9050"
    restart: always

  ssh-honeypot:
    build:
      context: .
      dockerfile: Dockerfile_ssh_honeypot
    ports:
      - "2223:2222"
    restart: always

  logging-agent:
    build:
      context: .
      dockerfile: Dockerfile_logging_agent
    ports:
      - "2222:2222"
    restart: always

  flask-api:
    build:
      context: .
      dockerfile: Dockerfile_flask_api
    ports:
      - "5000:5000"
    restart: always
