version: "3.8"

services:
  tor:
    build: tor
    ports:
      - "9050:9050"
    restart: always

  http-honeypot:
    build: http-honeypot
    ports:
      - "5000:5000"
    restart: always

  elasticsearch:
    build: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always

  logstash:
    build: logstash
    ports:
      - "5044:5044"
      - "5514:5514"
      - "9600:9600"
    restart: always

  kibana:
    build: kibana
    ports:
      - "5601:5601"
    restart: always
