version: '3.8'
services:

  tor:
    build: tor
    ports:
      - "9050:9050"

  http-honeypot:
    build: http-honeypot
    ports:
      - "5000:5000"

  # http-logging-agent:
  #   build: http-logging-agent