# Lightweight Linux distro as the base image
FROM alpine:latest

# Install required dependencies
RUN apk add --no-cache tor

# Copy Tor config
COPY config/torrc /etc/tor/

# Expose necessary ports
EXPOSE 9050 2222

# Start Tor service
CMD ["tor"]
